class TurkeyCities {
  static const Map<String, List<String>> cityDistricts = {
    'Adana': ['Seyhan', 'Yüreğir', 'Çukurova', 'Sarıçam', 'Ceyhan', 'Kozan', 'İmamoğlu', 'Karataş', 'Pozantı', 'Feke', 'Aladağ', 'Saimbeyli', 'Tufanbeyli', 'Yumurtalık'],
    'Adıyaman': ['Merkez', 'Besni', 'Gölbaşı', 'Kahta', 'Gerger', 'Samsat', 'Tut', 'Çelikhan', 'Sincik'],
    'Afyonkarahisar': ['Merkez', 'Bolvadin', 'Dinar', 'Emirdağ', 'Sandıklı', 'Şuhut', 'Çay', 'Başmakçı', 'Bayat', 'İscehisar', 'İhsaniye', 'Sinanpaşa', 'Sultandağı'],
    'Ağrı': ['Merkez', 'Doğubayazıt', 'Eleşkirt', 'Patnos', 'Tutak', 'Diyadin', 'Hamur', 'Taşlıçay'],
    'Amasya': ['Merkez', 'Merzifon', 'Suluova', 'Taşova', 'Göynücek', 'Gümüşhacıköy', 'Hamamözü'],
    'Ankara': ['Çankaya', 'Keçiören', 'Yenimahalle', 'Mamak', 'Etimesgut', 'Sincan', 'Gölbaşı', 'Polatlı', 'Çubuk', 'Kahramankazan', 'Beypazarı', 'Elmadağ', 'Haymana', 'Kızılcahamam', 'Nallıhan'],
    'Antalya': ['Muratpaşa', 'Kepez', 'Konyaaltı', 'Alanya', 'Manavgat', 'Serik', 'Kumluca', 'Kaş', 'Finike', 'Gazipaşa', 'Demre', 'Elmalı', 'Korkuteli', 'Kemer'],
    'Artvin': ['Merkez', 'Hopa', 'Borçka', 'Arhavi', 'Yusufeli', 'Şavşat', 'Ardanuç', 'Kemalpaşa'],
    'Aydın': ['Efeler', 'Nazilli', 'Söke', 'Kuşadası', 'Didim', 'İncirliova', 'Çine', 'Germencik', 'Bozdoğan', 'Karacasu', 'Köşk', 'Sultanhisar'],
    'Balıkesir': ['Karesi', 'Altıeylül', 'Bandırma', 'Edremit', 'Gönen', 'Burhaniye', 'Ayvalık', 'Susurluk', 'Bigadiç', 'Dursunbey', 'Erdek', 'Havran', 'İvrindi', 'Sındırgı'],
    'Bilecik': ['Merkez', 'Bozüyük', 'Söğüt', 'Osmaneli', 'Gölpazarı', 'Pazaryeri'],
    'Bingöl': ['Merkez', 'Genç', 'Solhan', 'Karlıova', 'Adaklı', 'Kiğı', 'Yedisu'],
    'Bitlis': ['Merkez', 'Tatvan', 'Ahlat', 'Güroymak', 'Adilcevaz', 'Hizan', 'Mutki'],
    'Bolu': ['Merkez', 'Gerede', 'Mudurnu', 'Mengen', 'Göynük', 'Yeniçağa', 'Dörtdivan'],
    'Burdur': ['Merkez', 'Bucak', 'Gölhisar', 'Tefenni', 'Yeşilova', 'Karamanlı', 'Çavdır'],
    'Bursa': ['Osmangazi', 'Yıldırım', 'Nilüfer', 'İnegöl', 'Gemlik', 'Mustafakemalpaşa', 'Mudanya', 'Orhangazi', 'Karacabey', 'Gürsu', 'Kestel', 'Yenişehir', 'Iznik'],
    'Çanakkale': ['Merkez', 'Biga', 'Çan', 'Gelibolu', 'Yenice', 'Ezine', 'Lapseki', 'Gökçeada', 'Bozcaada', 'Ayvacık', 'Bayramiç'],
    'Çankırı': ['Merkez', 'Çerkeş', 'Ilgaz', 'Kurşunlu', 'Şabanözü', 'Yapraklı'],
    'Çorum': ['Merkez', 'Sungurlu', 'Osmancık', 'İskilip', 'Alaca', 'Bayat', 'Kargı', 'Mecitözü'],
    'Denizli': ['Pamukkale', 'Merkezefendi', 'Çivril', 'Acıpayam', 'Tavas', 'Honaz', 'Sarayköy', 'Buldan', 'Kale', 'Çal', 'Serinhisar'],
    'Diyarbakır': ['Kayapınar', 'Bağlar', 'Yenişehir', 'Sur', 'Ergani', 'Bismil', 'Silvan', 'Çermik', 'Dicle', 'Hani', 'Kulp', 'Lice', 'Pasur'],
    'Edirne': ['Merkez', 'Keşan', 'Uzunköprü', 'İpsala', 'Havsa', 'Enez', 'Meriç', 'Süloğlu'],
    'Elazığ': ['Merkez', 'Kovancılar', 'Karakoçan', 'Palu', 'Baskil', 'Arıcak', 'Maden', 'Sivrice'],
    'Erzincan': ['Merkez', 'Tercan', 'Üzümlü', 'Refahiye', 'Çayırlı', 'İliç', 'Kemah', 'Kemaliye'],
    'Erzurum': ['Yakutiye', 'Palandöken', 'Aziziye', 'Oltu', 'Horasan', 'Pasinler', 'Hınıs', 'İspir', 'Karayazı', 'Narman', 'Olur', 'Şenkaya', 'Tortum'],
    'Eskişehir': ['Odunpazarı', 'Tepebaşı', 'Sivrihisar', 'Çifteler', 'Seyitgazi', 'Alpu', 'Beylikova', 'Mahmudiye', 'Mihalıççık'],
    'Gaziantep': ['Şahinbey', 'Şehitkamil', 'Nizip', 'İslahiye', 'Nurdağı', 'Oğuzeli', 'Arabam', 'Karkamış', 'Yavuzeli'],
    'Giresun': ['Merkez', 'Bulancak', 'Espiye', 'Görele', 'Tirebolu', 'Şebinkarahisar', 'Keşap', 'Dereli', 'Yağlıdere'],
    'Gümüşhane': ['Merkez', 'Kelkit', 'Şiran', 'Köse', 'Torul', 'Kürtün'],
    'Hakkari': ['Merkez', 'Yüksekova', 'Şemdinli', 'Çukurca', 'Derecik'],
    'Hatay': ['Antakya', 'İskenderun', 'Defne', 'Dörtyol', 'Samandağ', 'Kırıkhan', 'Reyhanlı', 'Arsuz', 'Altınözü', 'Belen', 'Erzin', 'Hassa', 'Payas', 'Yayla'],
    'Isparta': ['Merkez', 'Yalvaç', 'Eğirdir', 'Şarkikaraağaç', 'Gelendost', 'Keçiborlu', 'Senirkent', 'Sütçüler'],
    'Mersin': ['Akdeniz', 'Toroslar', 'Yenişehir', 'Mezitli', 'Tarsus', 'Erdemli', 'Silifke', 'Anamur', 'Aydıncık', 'Bozyazı', 'Gülnar', 'Mut'],
    'İstanbul': ['Kadıköy', 'Beşiktaş', 'Üsküdar', 'Fatih', 'Pendik', 'Ümraniye', 'Maltepe', 'Şişli', 'Beylikdüzü', 'Sarıyer', 'Ataşehir', 'Bakırköy', 'Esenyurt', 'Avcılar', 'Bağcılar', 'Bahçelievler', 'Başakşehir', 'Beykoz', 'Beyoğlu', 'Büyükçekmece', 'Çatalca', 'Çekmeköy', 'Esenler', 'Gaziosmanpaşa', 'Güngören', 'Kağıthane', 'Kartal', 'Küçükçekmece', 'Sancaktepe', 'Silivri', 'Sultanbeyli', 'Sultangazi', 'Şile', 'Tuzla', 'Zeytinburnu'],
    'İzmir': ['Konak', 'Bornova', 'Karşıyaka', 'Buca', 'Çiğli', 'Gaziemir', 'Ödemiş', 'Torbalı', 'Menemen', 'Urla', 'Çeşme', 'Bergama', 'Aliağa', 'Bayındır', 'Bayraklı', 'Dikili', 'Foça', 'Karaburun', 'Kemalpaşa', 'Kınık', 'Kiraz', 'Menderes', 'Narlıdere', 'Seferihisar', 'Selçuk', 'Tire', 'Foça'],
    'Kars': ['Merkez', 'Kağızman', 'Sarıkamış', 'Digor', 'Arpaçay', 'Selim', 'Susuz'],
    'Kastamonu': ['Merkez', 'Tosya', 'Taşköprü', 'Cide', 'İnebolu', 'Araç', 'Bozkurt', 'Daday', 'Devrekani', 'Küre'],
    'Kayseri': ['Melikgazi', 'Kocasinan', 'Talas', 'Develi', 'Yahyalı', 'Bünyan', 'Incesu', 'Pınarbaşı', 'Tomarza', 'Yeşilhisar'],
    'Kırklareli': ['Merkez', 'Lüleburgaz', 'Babaeski', 'Vize', 'Demirköy', 'Pınarhisar'],
    'Kırşehir': ['Merkez', 'Kaman', 'Mucur', 'Çiçekdağı'],
    'Kocaeli': ['İzmit', 'Gebze', 'Darıca', 'Körfez', 'Gölcük', 'Derince', 'Çayırova', 'Kartepe', 'Başiskele', 'Kandıra', 'Karamürsel'],
    'Konya': ['Karatay', 'Meram', 'Selçuklu', 'Ereğli', 'Akşehir', 'Beyşehir', 'Cihanbeyli', 'Çumra', 'Seydişehir', 'Kulu', 'Akören', 'Altınekin', 'Bozkır', 'Derebucak', 'Doğanhisar', 'Güneysınır', 'Hüyük', 'Ilgın', 'Kadınhanı', 'Karapınar', 'K Saray', 'Sarayönü', 'Yalıhüyük', 'Yunak'],
    'Kütahya': ['Merkez', 'Tavşanlı', 'Simav', 'Gediz', 'Emet', 'Domaniç', 'Altıntaş'],
    'Malatya': ['Yeşilyurt', 'Battalgazi', 'Doğanşehir', 'Darende', 'Akçadağ', 'Hekimhan', 'Pütürge', 'Yazıhan'],
    'Manisa': ['Şehzadeler', 'Yunusemre', 'Akhisar', 'Turgutlu', 'Salihli', 'Soma', 'Alaşehir', 'Kırkağaç', 'Demirci', 'Gördes', 'Kula', 'Saruhanlı', 'Sarıgöl'],
    'Kahramanmaraş': ['Onikişubat', 'Dulkadiroğlu', 'Elbistan', 'Afşin', 'Pazarcık', 'Göksun', 'Türkoğlu', 'Andırın'],
    'Mardin': ['Artuklu', 'Kızıltepe', 'Nusaybin', 'Midyat', 'Derik', 'Mazıdağı', 'Savur'],
    'Muğla': ['Menteşe', 'Bodrum', 'Fethiye', 'Milas', 'Marmaris', 'Seydikemer', 'Dalaman', 'Datça', 'Köyceğiz', 'Ortaca', 'Ula', 'Yatağan'],
    'Muş': ['Merkez', 'Bulanık', 'Malazgirt', 'Hasköy', 'Varto'],
    'Nevşehir': ['Merkez', 'Ürgüp', 'Avanos', 'Derinkuyu', 'Gülşehir', 'Hacıbektaş', 'Kozaklı'],
    'Niğde': ['Merkez', 'Bor', 'Çiftlik', 'Ulukışla', 'Altunhisar', 'Çamardı'],
    'Ordu': ['Altınordu', 'Ünye', 'Fatsa', 'Gölköy', 'Aybastı', 'Kumru', 'Korgan', 'Perşembe', 'Ulubey'],
    'Rize': ['Merkez', 'Çayeli', 'Ardeşen', 'Pazar', 'Fındıklı', 'Güneysu', 'İkizdere', 'Kalkandere'],
    'Sakarya': ['Adapazarı', 'Serdivan', 'Erenler', 'Hendek', 'Akyazı', 'Karasu', 'Geyve', 'Kocaali', 'Pamukova', 'Sapanca', 'Söğütlü'],
    'Samsun': ['İlkadım', 'Atakum', 'Canik', 'Bafra', 'Çarşamba', 'Vezirköprü', 'Alaçam', 'Havza', 'Kavak', 'Terme', 'Tekkeköy'],
    'Siirt': ['Merkez', 'Kurtalan', 'Pervari', 'Baykan', 'Eruh', 'Şirvan'],
    'Sinop': ['Merkez', 'Boyabat', 'Gerze', 'Ayancık', 'Durağan', 'Erfelek', 'Türkeli'],
    'Sivas': ['Merkez', 'Şarkışla', 'Yıldızeli', 'Suşehri', 'Zara', 'Divriği', 'Gürün', 'Kangal', 'Koyulhisar'],
    'Tekirdağ': ['Süleymanpaşa', 'Çorlu', 'Çerkezköy', 'Kapaklı', 'Ergene', 'Hayrabolu', 'Malkara', 'Marmaraereğlisi', 'Muratlı', 'Şarköy'],
    'Tokat': ['Merkez', 'Erbaa', 'Turhal', 'Niksar', 'Zile', 'Almus', 'Artova', 'Reşadiye'],
    'Trabzon': ['Ortahisar', 'Akçaabat', 'Araklı', 'Of', 'Yomra', 'Arsin', 'Beşikdüzü', 'Çarşıbaşı', 'Maçka', 'Sürmene', 'Vakfıkebir'],
    'Tunceli': ['Merkez', 'Pertek', 'Mazgirt', 'Çemişgezek', 'Hozat', 'Ovacık'],
    'Şanlıurfa': ['Haliliye', 'Eyyübiye', 'Karaköprü', 'Siverek', 'Viranşehir', 'Suruç', 'Birecik', 'Akçakale', 'Bozova', 'Ceylanpınar', 'Harran', 'Hilvan'],
    'Uşak': ['Merkez', 'Banaz', 'Eşme', 'Karahallı', 'Ulubey'],
    'Van': ['İpekyolu', 'Tuşba', 'Edremit', 'Erciş', 'Özalp', 'Başkale', 'Çaldıran', 'Gevaş', 'Muradiye'],
    'Yozgat': ['Merkez', 'Sorgun', 'Akdağmadeni', 'Yerköy', 'Boğazlıyan', 'Çayıralan', 'Sarıkaya'],
    'Zonguldak': ['Merkez', 'Ereğli', 'Çaycuma', 'Devrek', 'Alaplı', 'Gökçebey'],
    'Aksaray': ['Merkez', 'Ortaköy', 'Eskil', 'Gülağaç', 'Güzelyurt'],
    'Bayburt': ['Merkez', 'Aydıntepe', 'Demirözü'],
    'Karaman': ['Merkez', 'Ermenek', 'Sarıveliler', 'Başyayla', 'Kazımkarabekir'],
    'Kırıkkale': ['Merkez', 'Yahşihan', 'Keskin', 'Delice', 'Sulakyurt'],
    'Batman': ['Merkez', 'Kozluk', 'Sason', 'Beşiri', 'Gercüş', 'Hasankeyf'],
    'Şırnak': ['Merkez', 'Cizre', 'Silopi', 'İdil', 'Beytüşşebap', 'Uludere'],
    'Bartın': ['Merkez', 'Amasra', 'Ulus', 'Kurucaşile'],
    'Ardahan': ['Merkez', 'Göle', 'Çıldır', 'Posof'],
    'Iğdır': ['Merkez', 'Tuzluca', 'Aralık', 'Karakoyunlu'],
    'Yalova': ['Merkez', 'Çiftlikköy', 'Çınarcık', 'Altınova', 'Armutlu'],
    'Karabük': ['Merkez', 'Safranbolu', 'Yenice', 'Eskipazar'],
    'Kilis': ['Merkez', 'Elbeyli', 'Musabeyli', 'Polateli'],
    'Osmaniye': ['Merkez', 'Kadirli', 'Düziçi', 'Bahçe', 'Toprakkale'],
    'Düzce': ['Merkez', 'Akçakoca', 'Gölyaka', 'Çilimli', 'Cumayeri', 'Yığılca']
  };

  static List<String> get getCities => cityDistricts.keys.toList()..sort();

  static List<String> getDistrictsForCity(String city) {
    return cityDistricts[city] ?? ['Merkez'];
  }
}
